### ISSUE TITLE
Eliminate "All Our Magic is Made in San Francisco..."

### ISSUE THREAD

**Issue by reynoldsalec** [thinktandem/thinktandem.io#150]
It just ain't true anymore!!!

**Goals**
- Advantages of a distributed team
- Show our geographical "reach" (basically areas where we can meet with you, multi-state radii)

**Follow-ups**
- How can we use different geographical regions for SEO boosts?
- Consider listing Google Biz locations, list main "offices"
- Content generated for geographic areas.
- Inbound marketing through geo-based lists.

**Comment by dbungard** [comment]
**Concept**
![testing](https://user-images.githubusercontent.com/41634671/51861933-79684600-230b-11e9-9eb5-9bbbb9de4080.png)

**Map**
![map](https://user-images.githubusercontent.com/41634671/51861917-73726500-230b-11e9-8280-9436c2a65d35.png)

**Words**
We are a fully distributed team! What does that mean to you?

* We have access to the best talent, anywhere in the country
* A team member is working when you are, regardless of what coast you’re on
* Need to talk face-to-face, we’re a short drive or flight to most major cities

Ready to get to know us better?    [Lets Talk]


@labboy0276 let me know if you need anything

**Comment by labboy0276** [comment]
@reynoldsalec @dbungard https://pr-154-7x57u7q-femv4bu3mqicm.us.platform.sh/about/ LEt me know your thoughts

**Comment by dbungard** [comment]
🤔 now that I'm seeing this.. should it be
"anywhere in the country" or "anywhere in the world"
"what coast" or "which coast"

Otherwise awesome! Thank you @labboy0276
