### ISSUE TITLE
Francisco Tells Mike and Alec why they aren't designers

### ISSUE THREAD

**Issue by pirog** [thinktandem/thinktandem.io#3]
@mindbrain, let's use this as a place to dump all relevant feedback for the new site

cc: @reynoldsalec

**Comment by mindbrain** [comment]
@pirog @reynoldsalec wonderful. I'll begin today posting some thoughts.

**Comment by pirog** [comment]
@reynoldsalec @mindbrain, im going to drop in some high level bullets here just so we have some wider buckets to classify things by

### Front Page

* Vertical spacing between sections is weird
* "We do" items: single color? filled out background color vs bordered? right angle borders or curved?
* Client logos: some sort of standard presentation here? grayscale? something else?
* Quotes: Single color for all quotes or mix it up?
* Blog post titles: different color per author (like pop up quote on about us page)

### About us page

* Circular pics are lame?
* Vertical spacing here as well?

**Comment by pirog** [comment]
Put together some variants for us to check out
![screen shot 2017-08-31 at 10 45 35 pm](https://user-images.githubusercontent.com/713424/29956778-43381c2a-8e9e-11e7-996c-3e88f0ddc600.png)

**Comment by mindbrain** [comment]
Middle one is clear winner. going to see what it looks like with living texture and test some positioning.

**Comment by reynoldsalec** [comment]
RE: variants of services, I think I'm with @mindbrain on the middle one.

@mindbrain also curious if you have feedback on how we're using the headers on these homepage sections; feel like the centering of them breaks the left-justified feel we have elsewhere, but not sure if it looks quite right.

**Comment by mindbrain** [comment]
I'd stick mostly with left align. It might be nice to break it up with some left aligned headers every now and again. We could use left aligned callouts to break up the monotony if the need arises.

**Comment by mindbrain** [comment]
@alec also generally agree with you that centering throws it off a bit.
