### ISSUE TITLE
Blog stylingzzz?

### ISSUE THREAD

**Issue by pirog** [thinktandem/thinktandem.io#91]
It's super awesome that our blog page actually lists more than three articles now but i definitely preferred the minimal grid aesthetic we had going on previously vs what we have going on now. Anyone else feel like going back to the grid would be an improvement?

@Senpai @reynoldsalec @labboy0276 @serundeputy ?

**Comment by reynoldsalec** [comment]
Would be interested in seeing what the grid looks like with 6-9 entries, as long as that's not overload I'd prefer it.

**Comment by pirog** [comment]
@reynoldsalec i think the big thing would just be removing the byline and shipping with just title/author/date.

**Comment by serundeputy** [comment]
i'm werkin' on it.

**Comment by serundeputy** [comment]
@pirog griddified at 9: https://pr-92-zfngtwa-femv4bu3mqicm.us.platform.sh/blog/
